-- =============================================
-- SUMMIT PLANNER: VALIDATED OBJECTIVES (15)
-- Run this THIRD in Supabase SQL Editor
-- =============================================

-- 1. Half Dome
INSERT INTO validated_objectives (name, route, match_aliases, type, difficulty, description, summit_elevation_ft, total_gain_ft, distance_miles, duration_days, technical_grade, tags, target_scores, taglines, relevance_profiles, graduation_benchmarks, recommended_weeks, status) VALUES
('Half Dome', 'Mist Trail + Cables', '{"half dome", "half dome mist trail", "half dome cables", "half dome yosemite"}', 'hike', 'intermediate', 'Iconic Yosemite summit via the Mist Trail and cable route. 14-16 mile day with 4,800ft gain and the famous cable section.', 8844, 4800, 14.5, 1, 'Class 2-3 (cables)', '["heavy-pack", "exposure", "endurance", "long-day"]',
'{"cardio": 65, "strength": 45, "climbing_technical": 25, "flexibility": 30}',
'{"cardio": "All-day engine for big vert", "strength": "Legs and grip for cables", "climbing_technical": "Confidence on exposed cables", "flexibility": "Hip and ankle stamina"}',
'{"cardio": {"summary": "Half Dome demands sustained aerobic output over 10-14 hours.", "keyComponents": ["Sustained zone 2 hiking capacity", "Uphill endurance under load", "Ability to maintain pace at altitude", "Recovery between steep sections", "Heat management on exposed trail", "Late-day fatigue resistance", "Stair-climbing endurance", "Hydration and fueling strategy"], "irrelevantComponents": ["Sprint speed", "VO2 max intervals", "Cycling fitness", "Swimming endurance", "Track running form", "Rowing intervals", "Short burst power", "Anaerobic threshold work"]}, "strength": {"summary": "Cable section demands grip strength and upper body pulling. Legs need endurance for 4800ft of climbing.", "keyComponents": ["Loaded step-up endurance", "Single-leg strength and stability", "Grip endurance for cable section", "Core stability under pack load", "Downhill eccentric leg strength", "Push-up and shoulder endurance", "Squat depth and control", "Weighted carry capacity"], "irrelevantComponents": ["Maximal bench press", "Olympic lifting", "Bicep curl strength", "Calf raise max", "Lat pulldown max", "Machine-based isolation", "Powerlifting total", "Wrist curl strength"]}, "climbing_technical": {"summary": "The cable section is exposed but has fixed cables. Comfort with heights and basic scrambling confidence is essential.", "keyComponents": ["Comfort on exposed terrain", "Basic scrambling movement", "Cable/fixed-line technique", "Balance on uneven rock", "Route finding on granite slabs", "Confidence at height", "Efficient movement on rock steps"], "irrelevantComponents": ["Lead climbing ability", "Crack climbing technique", "Anchor building", "Multi-pitch rope management", "Ice climbing", "Aid climbing", "Belaying technique", "Trad gear placement"]}, "flexibility": {"summary": "Long day hiking requires adequate hip and ankle mobility.", "keyComponents": ["Hip flexor mobility for steep steps", "Ankle dorsiflexion for uphill", "Hamstring flexibility", "IT band and quad flexibility", "Lower back mobility", "Knee tracking and stability", "Calf flexibility"], "irrelevantComponents": ["Full splits", "Shoulder overhead mobility", "Wrist flexibility", "Advanced yoga poses", "Contortion flexibility", "Extreme backbend", "Side split range"]}}',
'{"cardio": [{"exerciseId": "b1000000-0000-0000-0000-000000000003", "exerciseName": "Uphill Hike with Pack", "graduationTarget": "1500 ft gain in 60 min with 15lb pack", "whyThisTarget": "Half Dome demands sustained uphill capacity for 4800ft total gain."}], "strength": [{"exerciseId": "b2000000-0000-0000-0000-000000000002", "exerciseName": "Single-Leg Step-Down", "graduationTarget": "20 per leg", "whyThisTarget": "Cable section and Mist Trail steps demand single-leg stability."}, {"exerciseId": "b2000000-0000-0000-0000-000000000005", "exerciseName": "Push-Up Max Set", "graduationTarget": "25 reps", "whyThisTarget": "Pulling on cables and pushing over rock requires upper body endurance."}], "climbing_technical": [{"exerciseId": "b3000000-0000-0000-0000-000000000002", "exerciseName": "Scramble Confidence Assessment", "graduationTarget": "3 out of 5", "whyThisTarget": "Cable section requires moderate comfort with exposure."}], "flexibility": [{"exerciseId": "b4000000-0000-0000-0000-000000000001", "exerciseName": "Deep Squat Hold", "graduationTarget": "45 seconds", "whyThisTarget": "Adequate hip and ankle mobility for steep terrain."}]}',
10, 'active');

-- 2. Colorado 14er Class 1-2
INSERT INTO validated_objectives (name, route, match_aliases, type, difficulty, description, summit_elevation_ft, total_gain_ft, distance_miles, duration_days, technical_grade, tags, target_scores, taglines, relevance_profiles, graduation_benchmarks, recommended_weeks, status) VALUES
('Colorado 14er (Class 1-2)', 'Standard Routes (Quandary, Elbert, Bierstadt)', '{"14er", "fourteener", "quandary peak", "mount elbert", "bierstadt", "colorado 14er", "14er class 1", "14er class 2"}', 'hike', 'beginner', 'Standard non-technical Colorado 14ers. Typically 6-14 miles with 3000-5000ft gain above 14,000ft.', 14265, 3500, 7, 1, 'Class 1-2', '["high-altitude", "endurance"]',
'{"cardio": 55, "strength": 35, "climbing_technical": 10, "flexibility": 25}',
'{"cardio": "Steady effort in thin mountain air", "strength": "Legs for sustained uphill", "climbing_technical": "Basic trail navigation", "flexibility": "Comfortable movement on trails"}',
'{"cardio": {"summary": "14ers demand sustained aerobic work at altitude where oxygen is reduced by 40%.", "keyComponents": ["Zone 2 hiking endurance", "Performance at altitude", "Uphill sustained pace", "Early morning cold starts", "Alpine start fitness", "Recovery during breaks", "Sustained effort over 4-8 hours", "Stairmaster or steep hiking"], "irrelevantComponents": ["Sprint intervals", "Track speed", "Swimming", "Rowing", "Cycling power", "Flat running speed", "Short-duration cardio", "Anaerobic capacity"]}, "strength": {"summary": "Moderate leg strength needed for sustained uphill hiking.", "keyComponents": ["Step-up endurance", "Squat endurance", "Single-leg balance", "Core hiking posture", "Downhill knee stability", "Calf endurance", "Hip hinge stability"], "irrelevantComponents": ["Max deadlift", "Bench press", "Olympic lifts", "Heavy overhead press", "Bicep isolation", "Machine work", "Powerlifting", "Heavy farmer carry"]}, "climbing_technical": {"summary": "Class 1-2 terrain requires no technical climbing skills.", "keyComponents": ["Trail following", "Talus/scree walking", "Basic route finding", "Weather awareness", "Pace management"], "irrelevantComponents": ["Rope skills", "Lead climbing", "Crack climbing", "Anchor building", "Multi-pitch technique", "Ice climbing", "Aid climbing", "Trad placement", "Sport clipping"]}, "flexibility": {"summary": "Basic hip and ankle mobility supports efficient hiking posture.", "keyComponents": ["Hip flexor range", "Ankle mobility", "Hamstring flexibility", "Calf flexibility", "Lower back mobility", "Knee comfort"], "irrelevantComponents": ["Full splits", "Extreme backbend", "Shoulder mobility", "Wrist flexibility", "Contortion", "Advanced yoga", "Overhead range"]}}',
'{"cardio": [{"exerciseId": "b1000000-0000-0000-0000-000000000003", "exerciseName": "Uphill Hike with Pack", "graduationTarget": "1200 ft gain in 60 min with 10lb pack", "whyThisTarget": "Standard 14er pace for non-technical routes."}], "strength": [{"exerciseId": "b2000000-0000-0000-0000-000000000002", "exerciseName": "Single-Leg Step-Down", "graduationTarget": "15 per leg", "whyThisTarget": "Basic single-leg stability for trail hiking."}], "climbing_technical": [{"exerciseId": "b3000000-0000-0000-0000-000000000002", "exerciseName": "Scramble Confidence Assessment", "graduationTarget": "2 out of 5", "whyThisTarget": "Minimal exposure on class 1-2 terrain."}], "flexibility": [{"exerciseId": "b4000000-0000-0000-0000-000000000001", "exerciseName": "Deep Squat Hold", "graduationTarget": "30 seconds", "whyThisTarget": "Basic mobility for hiking."}]}',
6, 'active');

-- 3. Mt. Whitney
INSERT INTO validated_objectives (name, route, match_aliases, type, difficulty, description, summit_elevation_ft, total_gain_ft, distance_miles, duration_days, technical_grade, tags, target_scores, taglines, relevance_profiles, graduation_benchmarks, recommended_weeks, status) VALUES
('Mt. Whitney', 'Main Trail (Whitney Trail)', '{"mt whitney", "mount whitney", "whitney", "whitney main trail", "whitney portal"}', 'hike', 'intermediate', 'Highest peak in the contiguous US via the Main Trail. 22-mile round trip with 6,100ft gain.', 14505, 6100, 22, 1, 'Class 1', '["high-altitude", "endurance", "long-day"]',
'{"cardio": 72, "strength": 45, "climbing_technical": 10, "flexibility": 30}',
'{"cardio": "Ultra-endurance at extreme altitude", "strength": "Legs for 6000ft of vert", "climbing_technical": "Simple trail navigation", "flexibility": "All-day mobility maintenance"}',
'{"cardio": {"summary": "Whitney is a massive day: 22 miles and 6100ft gain, much above 12,000ft.", "keyComponents": ["Zone 2 endurance beyond 4 hours", "High-altitude aerobic capacity", "Uphill hiking stamina", "Pre-dawn start fitness", "Sustained effort above 12000ft", "Recovery during switchbacks", "Heat and cold adaptation", "Fueling on long efforts"], "irrelevantComponents": ["Sprint speed", "VO2 max intervals", "Swimming", "Short-burst cardio", "Cycling power output", "Track intervals", "Rowing sprints", "Anaerobic work"]}, "strength": {"summary": "6100ft of gain demands exceptional leg endurance.", "keyComponents": ["Step-up endurance for hours", "Single-leg stability", "Core endurance under pack", "Downhill eccentric control", "Squat endurance", "Calf endurance", "Hip stability", "Glute endurance"], "irrelevantComponents": ["Max bench press", "Olympic lifts", "Heavy deadlift", "Bicep curls", "Machine isolation", "Powerlifting", "Upper body max", "Wrist curls"]}, "climbing_technical": {"summary": "Main Trail is Class 1.", "keyComponents": ["Trail following", "Switchback navigation", "Night hiking with headlamp", "Basic weather awareness", "Talus navigation near summit"], "irrelevantComponents": ["Rope skills", "Rock climbing grades", "Anchor building", "Lead climbing", "Crack climbing", "Ice techniques", "Multi-pitch", "Aid climbing", "Trad placement"]}, "flexibility": {"summary": "Long day demands mobility to prevent tightening over many hours.", "keyComponents": ["Hip flexor range", "Ankle mobility", "Hamstring flexibility", "IT band flexibility", "Calf flexibility", "Lower back range"], "irrelevantComponents": ["Full splits", "Extreme backbend", "Shoulder overhead range", "Wrist flexibility", "Contortion", "Advanced yoga"]}}',
'{"cardio": [{"exerciseId": "b1000000-0000-0000-0000-000000000002", "exerciseName": "Sustained Zone 2 Run", "graduationTarget": "12 miles at zone 2 pace", "whyThisTarget": "Whitney demands 12-16 hours of sustained aerobic effort."}, {"exerciseId": "b1000000-0000-0000-0000-000000000003", "exerciseName": "Uphill Hike with Pack", "graduationTarget": "1800 ft gain in 60 min with 15lb pack", "whyThisTarget": "Must sustain high output uphill for 6100ft total."}], "strength": [{"exerciseId": "b2000000-0000-0000-0000-000000000001", "exerciseName": "Loaded Pack Squat", "graduationTarget": "15 reps at bodyweight", "whyThisTarget": "Leg endurance for thousands of steps."}, {"exerciseId": "b2000000-0000-0000-0000-000000000002", "exerciseName": "Single-Leg Step-Down", "graduationTarget": "20 per leg", "whyThisTarget": "Single-leg stability for switchbacks."}], "climbing_technical": [{"exerciseId": "b3000000-0000-0000-0000-000000000002", "exerciseName": "Scramble Confidence Assessment", "graduationTarget": "2 out of 5", "whyThisTarget": "Minimal technical terrain."}], "flexibility": [{"exerciseId": "b4000000-0000-0000-0000-000000000001", "exerciseName": "Deep Squat Hold", "graduationTarget": "45 seconds", "whyThisTarget": "Adequate mobility for long hiking day."}]}',
12, 'active');

-- 4. Mont Blanc
INSERT INTO validated_objectives (name, route, match_aliases, type, difficulty, description, summit_elevation_ft, total_gain_ft, distance_miles, duration_days, technical_grade, tags, target_scores, taglines, relevance_profiles, graduation_benchmarks, recommended_weeks, status) VALUES
('Mont Blanc', 'Goûter Route (Voie Normale)', '{"mont blanc", "mont blanc normal route", "mont blanc gouter", "mont blanc from saint-gervais"}', 'mountaineering', 'advanced', 'Highest peak in the Alps via the standard Goûter Route. 2-day climb with glacier travel and altitude sickness risk.', 15781, 5200, 11, 2, 'PD', '["high-altitude", "glacier", "multi-day", "heavy-pack"]',
'{"cardio": 78, "strength": 58, "climbing_technical": 35, "flexibility": 40}',
'{"cardio": "Sustained effort in thin air", "strength": "Power through steep icy terrain", "climbing_technical": "Glacier and crampon confidence", "flexibility": "Move efficiently in heavy boots"}',
'{"cardio": {"summary": "Mont Blanc demands sustained high-output effort above 4000m.", "keyComponents": ["Zone 2 endurance beyond 6 hours", "Performance above 4000m altitude", "Uphill capacity with heavy pack", "Cold-weather breathing efficiency", "Pre-dawn alpine start fitness", "Recovery at altitude", "Sustained pace on snow/ice", "Multi-day recovery between efforts"], "irrelevantComponents": ["Sprint speed", "Track intervals", "Swimming fitness", "Flat road running pace", "Cycling power", "Short-burst intervals", "Rowing sprints", "Anaerobic capacity"]}, "strength": {"summary": "Climbing with crampons on steep snow/ice demands leg strength plus 25-35lb pack for 2 days.", "keyComponents": ["Loaded pack squats for steep terrain", "Single-leg stability on ice", "Crampon kick-step power", "Core stability in high winds", "Grip for ice axe self-arrest", "Shoulder endurance for pack carry", "Step-up power with boots and crampons", "Weighted carry endurance"], "irrelevantComponents": ["Bench press max", "Bicep curls", "Machine isolation exercises", "Lat pulldown max", "Leg press machine", "Wrist curls", "Calf raise machine", "Cable crossovers"]}, "climbing_technical": {"summary": "Goûter route requires crampon technique, ice axe use, and rope travel on glaciers.", "keyComponents": ["Crampon walking technique", "Ice axe self-arrest", "Roped glacier travel", "Basic crevasse rescue awareness", "Moving on 35-45 degree snow", "Fixed-line technique", "Route finding in whiteout conditions"], "irrelevantComponents": ["Sport lead climbing", "Crack climbing technique", "Bouldering problems", "Multi-pitch free climbing", "Aid climbing", "Trad gear placement on rock", "Advanced anchor building"]}, "flexibility": {"summary": "Heavy boots and crampons restrict ankle mobility. Hip and hamstring flexibility is essential.", "keyComponents": ["Hip flexor mobility for high steps", "Ankle dorsiflexion in stiff boots", "Hamstring range for steep terrain", "Lower back mobility under pack", "Hip rotation for traversing", "Calf flexibility in boots", "Knee tracking with crampons"], "irrelevantComponents": ["Full splits", "Extreme backbend", "Shoulder overhead range", "Wrist flexibility", "Contortion", "Advanced yoga poses", "Side split flexibility"]}}',
'{"cardio": [{"exerciseId": "b1000000-0000-0000-0000-000000000001", "exerciseName": "Timed Loaded Step-Ups", "graduationTarget": "450 reps in 30 min with 30lb pack", "whyThisTarget": "Mont Blanc demands sustained uphill capacity with heavy pack at altitude."}, {"exerciseId": "b1000000-0000-0000-0000-000000000002", "exerciseName": "Sustained Zone 2 Run", "graduationTarget": "10 miles at zone 2", "whyThisTarget": "Aerobic base for 8-12 hour summit days."}], "strength": [{"exerciseId": "b2000000-0000-0000-0000-000000000001", "exerciseName": "Loaded Pack Squat", "graduationTarget": "20 reps at 1.25x bodyweight", "whyThisTarget": "Steep snow/ice demands strong legs under load."}, {"exerciseId": "b2000000-0000-0000-0000-000000000003", "exerciseName": "Weighted Pull-Ups", "graduationTarget": "8 bodyweight pull-ups", "whyThisTarget": "Ice axe use and pulling over obstacles."}, {"exerciseId": "b2000000-0000-0000-0000-000000000004", "exerciseName": "Loaded Carry", "graduationTarget": "400m with 50lb in 10 min", "whyThisTarget": "Must carry heavy pack for multi-day approach."}], "climbing_technical": [{"exerciseId": "b3000000-0000-0000-0000-000000000002", "exerciseName": "Scramble Confidence Assessment", "graduationTarget": "4 out of 5", "whyThisTarget": "Exposed glacier and ridge terrain requires confidence."}], "flexibility": [{"exerciseId": "b4000000-0000-0000-0000-000000000001", "exerciseName": "Deep Squat Hold", "graduationTarget": "60 seconds", "whyThisTarget": "Hip and ankle mobility for crampon technique."}, {"exerciseId": "b4000000-0000-0000-0000-000000000002", "exerciseName": "Hip Flexor Stretch Assessment", "graduationTarget": "4 out of 5", "whyThisTarget": "Must maintain hip range in stiff boots."}]}',
14, 'active');

-- 5. Mt. Rainier
INSERT INTO validated_objectives (name, route, match_aliases, type, difficulty, description, summit_elevation_ft, total_gain_ft, distance_miles, duration_days, technical_grade, tags, target_scores, taglines, relevance_profiles, graduation_benchmarks, recommended_weeks, status) VALUES
('Mt. Rainier', 'Disappointment Cleaver', '{"mt rainier", "mount rainier", "rainier", "rainier dc", "disappointment cleaver"}', 'mountaineering', 'advanced', 'Pacific Northwest iconic volcano via the standard DC route. 2-3 day climb with glacier travel.', 14411, 9000, 16, 2, 'PD-', '["high-altitude", "glacier", "multi-day", "heavy-pack"]',
'{"cardio": 75, "strength": 60, "climbing_technical": 40, "flexibility": 38}',
'{"cardio": "Relentless vertical in Pacific storms", "strength": "Carry heavy through steep ice", "climbing_technical": "Rope teams on active glaciers", "flexibility": "Efficient crampon movement all day"}',
'{"cardio": {"summary": "Rainier has 9000ft of gain, much on steep snow and ice.", "keyComponents": ["Sustained uphill capacity for 9000ft", "Pre-dawn alpine start fitness", "Performance above 12000ft", "Multi-day endurance", "Zone 2 capacity for 8+ hours", "Recovery between climb days", "Cold-weather cardio efficiency", "Steep snow hiking pace"], "irrelevantComponents": ["Sprint speed", "Track intervals", "Swimming", "Flat running speed", "Cycling sprints", "Rowing intervals", "Short-burst power", "Anaerobic threshold"]}, "strength": {"summary": "Carrying 35-50lb pack up steep snow demands exceptional leg and core strength.", "keyComponents": ["Heavy pack squat strength", "Single-leg stability on ice", "Core under heavy load", "Grip for ice axe arrest", "Step-up power with crampons", "Weighted carry endurance", "Shoulder endurance for pack", "Eccentric downhill control"], "irrelevantComponents": ["Bench press max", "Bicep isolation", "Machine exercises", "Cable work", "Leg extension machine", "Wrist curls", "Lat pulldown max", "Calf raise machine"]}, "climbing_technical": {"summary": "DC route requires glacier travel, crampon technique, fixed lines, and crevasse awareness.", "keyComponents": ["Crampon proficiency all angles", "Ice axe self-arrest", "Roped glacier travel", "Crevasse rescue basics", "Fixed-line ascending", "Route finding on glaciers", "Moving at night with headlamp"], "irrelevantComponents": ["Sport climbing grades", "Crack climbing", "Bouldering", "Multi-pitch free climbing", "Aid climbing", "Trad placement", "Advanced anchor building"]}, "flexibility": {"summary": "Heavy boots and crampons demand good hip and ankle mobility.", "keyComponents": ["Hip flexor mobility", "Ankle range in boots", "Hamstring flexibility", "Lower back under load", "Hip rotation for kick-steps", "Calf flexibility", "Knee tracking"], "irrelevantComponents": ["Full splits", "Extreme backbend", "Overhead shoulder range", "Wrist flexibility", "Contortion", "Advanced yoga", "Side splits"]}}',
'{"cardio": [{"exerciseId": "b1000000-0000-0000-0000-000000000001", "exerciseName": "Timed Loaded Step-Ups", "graduationTarget": "500 reps in 30 min with 35lb pack", "whyThisTarget": "Rainier demands exceptional uphill capacity with heavy pack."}, {"exerciseId": "b1000000-0000-0000-0000-000000000002", "exerciseName": "Sustained Zone 2 Run", "graduationTarget": "12 miles at zone 2", "whyThisTarget": "Base aerobic capacity for multi-day effort."}], "strength": [{"exerciseId": "b2000000-0000-0000-0000-000000000001", "exerciseName": "Loaded Pack Squat", "graduationTarget": "15 reps at 1.25x bodyweight", "whyThisTarget": "Heavy pack on steep terrain."}, {"exerciseId": "b2000000-0000-0000-0000-000000000004", "exerciseName": "Loaded Carry", "graduationTarget": "450m with 60lb in 10 min", "whyThisTarget": "Must carry heavy pack for approach."}, {"exerciseId": "b2000000-0000-0000-0000-000000000003", "exerciseName": "Weighted Pull-Ups", "graduationTarget": "5 at +15lb", "whyThisTarget": "Upper body for ice axe and fixed lines."}], "climbing_technical": [{"exerciseId": "b3000000-0000-0000-0000-000000000002", "exerciseName": "Scramble Confidence Assessment", "graduationTarget": "4 out of 5", "whyThisTarget": "Glacier exposure requires high confidence."}], "flexibility": [{"exerciseId": "b4000000-0000-0000-0000-000000000001", "exerciseName": "Deep Squat Hold", "graduationTarget": "60 seconds", "whyThisTarget": "Hip and ankle range for crampons."}]}',
14, 'active');

-- 6. Denali
INSERT INTO validated_objectives (name, route, match_aliases, type, difficulty, description, summit_elevation_ft, total_gain_ft, distance_miles, duration_days, technical_grade, tags, target_scores, taglines, relevance_profiles, graduation_benchmarks, recommended_weeks, status) VALUES
('Denali', 'West Buttress', '{"denali", "denali west buttress", "mt mckinley", "mount mckinley"}', 'mountaineering', 'expert', 'Highest peak in North America. 17-21 day expedition with extreme altitude, cold, and heavy loads.', 20310, 13000, 32, 18, 'AD-', '["high-altitude", "glacier", "multi-day", "heavy-pack", "extreme-cold"]',
'{"cardio": 88, "strength": 75, "climbing_technical": 55, "flexibility": 45}',
'{"cardio": "Weeks of effort in extreme thin air", "strength": "Move house up a mountain", "climbing_technical": "Full alpine skill set required", "flexibility": "Survive weeks in heavy gear"}',
'{"cardio": {"summary": "Denali requires 2-3 weeks of sustained effort at extreme altitude.", "keyComponents": ["Multi-week sustained effort", "Performance above 17000ft", "Recovery between carry days", "Cold-weather cardio efficiency", "Uphill capacity with extreme loads", "Zone 2 endurance 6+ hours daily", "Altitude acclimatization capacity", "Rest day utilization"], "irrelevantComponents": ["Sprint speed", "Track intervals", "Swimming", "Cycling power", "Short-burst cardio", "Rowing sprints", "Flat running speed", "Anaerobic work"]}, "strength": {"summary": "Carrying 80-120lb total up steep snow and ice for weeks demands elite strength-endurance.", "keyComponents": ["Heavy pack carry endurance", "Sled-pulling strength", "Deep squat under extreme load", "Single-leg stability on ice", "Core strength for sled hauling", "Grip endurance in extreme cold", "Shoulder endurance for weeks", "Full-body fatigue resistance"], "irrelevantComponents": ["Bench press 1RM", "Bicep isolation", "Machine exercises", "Cable work", "Leg extension", "Wrist curls", "Lat pulldown max", "Calf raise machine"]}, "climbing_technical": {"summary": "West Buttress requires full glacier travel skills and camp management in extreme conditions.", "keyComponents": ["Advanced crampon technique", "Ice axe proficiency all conditions", "Fixed-line ascending/descending", "Crevasse rescue skills", "Camp management in storms", "Rope team travel efficiency", "Route finding in whiteout"], "irrelevantComponents": ["Sport climbing grades", "Bouldering", "Crack climbing", "Multi-pitch free climbing", "Aid climbing", "Trad rock placement", "Top-rope climbing"]}, "flexibility": {"summary": "Weeks in heavy boots and cramped tents demand flexibility maintenance.", "keyComponents": ["Hip flexor maintenance", "Ankle mobility in boots", "Hamstring range", "Lower back health", "Hip rotation range", "Shoulder mobility for pack adjustments", "Neck and upper back mobility"], "irrelevantComponents": ["Full splits", "Extreme backbend", "Contortion", "Advanced yoga", "Dance flexibility", "Gymnastics range"]}}',
'{"cardio": [{"exerciseId": "b1000000-0000-0000-0000-000000000001", "exerciseName": "Timed Loaded Step-Ups", "graduationTarget": "600 reps in 30 min with 40lb pack", "whyThisTarget": "Denali demands elite uphill capacity."}, {"exerciseId": "b1000000-0000-0000-0000-000000000002", "exerciseName": "Sustained Zone 2 Run", "graduationTarget": "15 miles at zone 2", "whyThisTarget": "Multi-week expedition requires deep aerobic base."}], "strength": [{"exerciseId": "b2000000-0000-0000-0000-000000000001", "exerciseName": "Loaded Pack Squat", "graduationTarget": "15 reps at 1.5x bodyweight", "whyThisTarget": "Extreme loads on steep terrain."}, {"exerciseId": "b2000000-0000-0000-0000-000000000004", "exerciseName": "Loaded Carry", "graduationTarget": "500m with 70lb in 10 min", "whyThisTarget": "Must carry and haul extreme loads."}, {"exerciseId": "b2000000-0000-0000-0000-000000000003", "exerciseName": "Weighted Pull-Ups", "graduationTarget": "5 at +25lb", "whyThisTarget": "Fixed lines and hauling."}], "climbing_technical": [{"exerciseId": "b3000000-0000-0000-0000-000000000002", "exerciseName": "Scramble Confidence Assessment", "graduationTarget": "5 out of 5", "whyThisTarget": "Extreme exposure."}, {"exerciseId": "b3000000-0000-0000-0000-000000000003", "exerciseName": "Rope Skills Timed Test", "graduationTarget": "12 minutes", "whyThisTarget": "Must be proficient with rope systems."}], "flexibility": [{"exerciseId": "b4000000-0000-0000-0000-000000000001", "exerciseName": "Deep Squat Hold", "graduationTarget": "90 seconds", "whyThisTarget": "Maintain mobility over weeks."}, {"exerciseId": "b4000000-0000-0000-0000-000000000002", "exerciseName": "Hip Flexor Stretch Assessment", "graduationTarget": "4 out of 5", "whyThisTarget": "Prevent hip tightness from weeks in boots."}]}',
20, 'active');

-- 7. Grand Teton
INSERT INTO validated_objectives (name, route, match_aliases, type, difficulty, description, summit_elevation_ft, total_gain_ft, distance_miles, duration_days, technical_grade, tags, target_scores, taglines, relevance_profiles, graduation_benchmarks, recommended_weeks, status) VALUES
('Grand Teton', 'Upper Exum Ridge', '{"grand teton", "grand teton exum", "exum ridge", "upper exum"}', 'alpine_climb', 'advanced', 'Classic alpine rock climb in the Tetons. Technical 5.5 climbing with serious exposure.', 13775, 7000, 12, 1, '5.5', '["trad-climbing", "exposure", "alpine", "heavy-pack"]',
'{"cardio": 68, "strength": 55, "climbing_technical": 65, "flexibility": 40}',
'{"cardio": "Big day approach plus climbing", "strength": "Pull and push on steep rock", "climbing_technical": "Multi-pitch alpine rock mastery", "flexibility": "Move freely on steep granite"}',
'{"cardio": {"summary": "Grand Teton requires a big approach hike plus sustained climbing.", "keyComponents": ["Sustained effort for 12+ hours", "Uphill approach with climbing gear", "Altitude performance above 12000ft", "Recovery between pitches", "Zone 2 for approach", "Late-day climbing endurance", "Cold morning fitness", "Efficient breathing on rock"], "irrelevantComponents": ["Sprint speed", "Swimming", "Cycling power", "Short intervals", "Flat running", "Rowing sprints", "Track work", "Anaerobic intervals"]}, "strength": {"summary": "Technical climbing at 5.5 on granite demands upper body pulling and leg press power.", "keyComponents": ["Pull-up strength for cruxes", "Core tension on steep terrain", "Grip endurance for long pitches", "Leg pressing on small footholds", "Shoulder endurance for rope management", "Lock-off strength", "Push-up power for mantles", "Single-leg power for high steps"], "irrelevantComponents": ["Bench press max", "Bicep curls", "Machine isolation", "Heavy deadlift", "Leg press machine", "Calf raises", "Cable work", "Wrist curls"]}, "climbing_technical": {"summary": "Upper Exum is sustained 5.4-5.5 alpine climbing with multi-pitch rope management.", "keyComponents": ["Multi-pitch climbing at 5.5", "Route finding on alpine terrain", "Anchor building efficiency", "Rope management on ledges", "Belaying in alpine setting", "Exposure comfort at height", "Efficient movement on granite"], "irrelevantComponents": ["Sport climbing at high grades", "Bouldering power", "Crack climbing harder than 5.6", "Aid climbing", "Ice climbing", "Indoor gym training", "Competition climbing"]}, "flexibility": {"summary": "High steps on granite require good hip and hamstring flexibility.", "keyComponents": ["Hip flexor range for high steps", "Hamstring flexibility for stemming", "Hip rotation for stemming", "Ankle mobility on small edges", "Shoulder range for reaching", "Lower back flexibility", "Knee comfort in chimney moves"], "irrelevantComponents": ["Full splits", "Extreme backbend", "Wrist flexibility", "Contortion", "Advanced yoga", "Dance flexibility", "Side splits"]}}',
'{"cardio": [{"exerciseId": "b1000000-0000-0000-0000-000000000003", "exerciseName": "Uphill Hike with Pack", "graduationTarget": "1800 ft gain in 60 min with 25lb pack", "whyThisTarget": "Approach with climbing gear."}], "strength": [{"exerciseId": "b2000000-0000-0000-0000-000000000003", "exerciseName": "Weighted Pull-Ups", "graduationTarget": "8 bodyweight pull-ups", "whyThisTarget": "Pulling on steep granite."}, {"exerciseId": "b2000000-0000-0000-0000-000000000005", "exerciseName": "Push-Up Max Set", "graduationTarget": "35 reps", "whyThisTarget": "Mantling and pressing moves."}], "climbing_technical": [{"exerciseId": "b3000000-0000-0000-0000-000000000001", "exerciseName": "Top-Rope Climbing Assessment", "graduationTarget": "Clean 5.7 outdoors", "whyThisTarget": "Must climb 5.5 confidently with pack."}, {"exerciseId": "b3000000-0000-0000-0000-000000000003", "exerciseName": "Rope Skills Timed Test", "graduationTarget": "15 minutes", "whyThisTarget": "Efficient rope management on multi-pitch."}], "flexibility": [{"exerciseId": "b4000000-0000-0000-0000-000000000001", "exerciseName": "Deep Squat Hold", "graduationTarget": "60 seconds", "whyThisTarget": "Hip and ankle range for climbing."}]}',
12, 'active');

-- 8. Cathedral Peak
INSERT INTO validated_objectives (name, route, match_aliases, type, difficulty, description, summit_elevation_ft, total_gain_ft, distance_miles, duration_days, technical_grade, tags, target_scores, taglines, relevance_profiles, graduation_benchmarks, recommended_weeks, status) VALUES
('Cathedral Peak', 'Southeast Buttress', '{"cathedral peak", "cathedral peak se buttress", "cathedral peak tuolumne"}', 'rock_climb', 'intermediate', 'Classic Tuolumne granite climb. 5-6 pitches at 5.6.', 10911, 2800, 8, 1, '5.6', '["trad-climbing", "exposure", "granite"]',
'{"cardio": 50, "strength": 48, "climbing_technical": 55, "flexibility": 35}',
'{"cardio": "Moderate approach plus climbing day", "strength": "Pull hard on Tuolumne knobs", "climbing_technical": "Multi-pitch trad on perfect granite", "flexibility": "Reach and stem on steep face"}',
'{"cardio": {"summary": "Cathedral Peak has a moderate approach. Not as cardio-demanding as bigger peaks.", "keyComponents": ["Moderate uphill approach capacity", "Recovery between pitches", "Sustained effort for 8-10 hours", "Altitude performance at 10000ft", "Efficient breathing while climbing", "Descent endurance", "Heat management on granite"], "irrelevantComponents": ["Ultra endurance", "Sprint speed", "Swimming", "Cycling", "Rowing", "Track intervals", "Heavy pack cardio", "Extreme altitude"]}, "strength": {"summary": "5.6 Tuolumne climbing demands moderate upper body and good footwork.", "keyComponents": ["Pull-up strength", "Grip endurance on granite", "Core tension for face climbing", "Foot pressing power on knobs", "Lock-off ability", "Shoulder endurance", "Push-up strength for mantles"], "irrelevantComponents": ["Heavy deadlift", "Bench press max", "Olympic lifts", "Machine isolation", "Heavy carries", "Leg press max", "Bicep curls", "Calf raises"]}, "climbing_technical": {"summary": "Multi-pitch trad at 5.6 on granite requires placement and route finding.", "keyComponents": ["Trad gear placement", "Anchor building", "Multi-pitch management", "Route finding on granite", "Belay transitions", "Knob climbing technique", "Exposure comfort on face climbs"], "irrelevantComponents": ["Ice climbing", "Aid climbing", "Crack climbing above 5.8", "Competition climbing", "Bouldering power", "Sport climbing chains", "Indoor training"]}, "flexibility": {"summary": "Face climbing requires good hip range for high steps.", "keyComponents": ["Hip flexibility for high steps", "Hamstring range", "Hip rotation for stemming", "Ankle mobility", "Shoulder reach", "Lower back flexibility"], "irrelevantComponents": ["Full splits", "Extreme backbend", "Contortion", "Wrist flexibility", "Dance flexibility", "Advanced yoga"]}}',
'{"cardio": [{"exerciseId": "b1000000-0000-0000-0000-000000000003", "exerciseName": "Uphill Hike with Pack", "graduationTarget": "1200 ft gain in 60 min with 20lb pack", "whyThisTarget": "Moderate approach with climbing gear."}], "strength": [{"exerciseId": "b2000000-0000-0000-0000-000000000003", "exerciseName": "Weighted Pull-Ups", "graduationTarget": "6 bodyweight pull-ups", "whyThisTarget": "Pulling on granite."}, {"exerciseId": "b2000000-0000-0000-0000-000000000005", "exerciseName": "Push-Up Max Set", "graduationTarget": "30 reps", "whyThisTarget": "Mantling and pressing."}], "climbing_technical": [{"exerciseId": "b3000000-0000-0000-0000-000000000001", "exerciseName": "Top-Rope Climbing Assessment", "graduationTarget": "Clean 5.8 outdoors", "whyThisTarget": "Must climb 5.6 confidently."}, {"exerciseId": "b3000000-0000-0000-0000-000000000003", "exerciseName": "Rope Skills Timed Test", "graduationTarget": "15 minutes", "whyThisTarget": "Efficient trad transitions."}], "flexibility": [{"exerciseId": "b4000000-0000-0000-0000-000000000001", "exerciseName": "Deep Squat Hold", "graduationTarget": "45 seconds", "whyThisTarget": "Hip range for face climbing."}]}',
10, 'active');

-- 9. Trail Half Marathon
INSERT INTO validated_objectives (name, route, match_aliases, type, difficulty, description, summit_elevation_ft, total_gain_ft, distance_miles, duration_days, technical_grade, tags, target_scores, taglines, relevance_profiles, graduation_benchmarks, recommended_weeks, status) VALUES
('Trail Half Marathon', '~4,000ft Gain', '{"trail half marathon", "trail half", "half marathon trail"}', 'trail_run', 'intermediate', 'Trail half marathon with approximately 4,000ft of elevation gain.', null, 4000, 13.1, 1, null, '["running", "endurance", "trail"]',
'{"cardio": 68, "strength": 40, "climbing_technical": 8, "flexibility": 32}',
'{"cardio": "Fast sustained uphill running", "strength": "Quick legs on technical trail", "climbing_technical": "Minimal — just trail running", "flexibility": "Fluid stride over roots and rocks"}',
'{"cardio": {"summary": "Trail half marathon demands strong running fitness with sustained climbs.", "keyComponents": ["Zone 2 running endurance", "Uphill running power", "Downhill running technique", "Trail pace management", "Heat adaptation", "Fueling during effort", "Sustained effort 2-4 hours", "Threshold running capacity"], "irrelevantComponents": ["Swimming", "Cycling power", "Rowing", "Sprint speed", "Ultra-distance", "Heavy pack hiking", "Altitude performance", "Multi-day endurance"]}, "strength": {"summary": "Trail running demands moderate leg strength for ups and downs.", "keyComponents": ["Single-leg stability", "Downhill eccentric control", "Core running posture", "Calf endurance", "Quad endurance on descents", "Hip stability running", "Ankle strength"], "irrelevantComponents": ["Heavy squats", "Bench press", "Pull-ups", "Heavy carries", "Olympic lifts", "Machine isolation", "Upper body max", "Grip strength"]}, "climbing_technical": {"summary": "No technical climbing needed.", "keyComponents": ["Trail navigation", "Root and rock avoidance", "Night running with light"], "irrelevantComponents": ["Rope skills", "Rock climbing", "Scrambling", "Anchor building", "Glacier travel", "Ice climbing", "Aid climbing", "Trad placement", "Crevasse rescue"]}, "flexibility": {"summary": "Running stride efficiency requires good hip and hamstring flexibility.", "keyComponents": ["Hip flexor range", "Hamstring flexibility", "IT band flexibility", "Ankle dorsiflexion", "Calf flexibility", "Quad flexibility"], "irrelevantComponents": ["Full splits", "Extreme backbend", "Shoulder overhead", "Wrist flexibility", "Contortion", "Advanced yoga"]}}',
'{"cardio": [{"exerciseId": "b1000000-0000-0000-0000-000000000002", "exerciseName": "Sustained Zone 2 Run", "graduationTarget": "10 miles at zone 2 pace", "whyThisTarget": "Must cover half marathon distance with significant climbing."}], "strength": [{"exerciseId": "b2000000-0000-0000-0000-000000000002", "exerciseName": "Single-Leg Step-Down", "graduationTarget": "20 per leg", "whyThisTarget": "Trail running demands single-leg stability."}], "climbing_technical": [{"exerciseId": "b3000000-0000-0000-0000-000000000002", "exerciseName": "Scramble Confidence Assessment", "graduationTarget": "1 out of 5", "whyThisTarget": "No scrambling needed."}], "flexibility": [{"exerciseId": "b4000000-0000-0000-0000-000000000001", "exerciseName": "Deep Squat Hold", "graduationTarget": "30 seconds", "whyThisTarget": "Basic hip mobility for running."}]}',
8, 'active');

-- 10. 50K Mountain Ultra
INSERT INTO validated_objectives (name, route, match_aliases, type, difficulty, description, summit_elevation_ft, total_gain_ft, distance_miles, duration_days, technical_grade, tags, target_scores, taglines, relevance_profiles, graduation_benchmarks, recommended_weeks, status) VALUES
('50K Mountain Ultra', '~8,000ft Gain', '{"50k ultra", "50k mountain ultra", "ultramarathon", "ultra trail", "50k trail"}', 'trail_run', 'advanced', 'Mountain ultramarathon with approximately 8,000ft of elevation gain over 31 miles.', null, 8000, 31, 1, null, '["running", "ultra-endurance", "trail"]',
'{"cardio": 82, "strength": 50, "climbing_technical": 8, "flexibility": 35}',
'{"cardio": "Relentless mountain running all day", "strength": "Durable legs for 31 miles", "climbing_technical": "Trail awareness only", "flexibility": "Keep moving after hours of pounding"}',
'{"cardio": {"summary": "50K ultra demands elite running endurance for 6-12+ hours.", "keyComponents": ["Zone 2 capacity beyond 4 hours", "Uphill running power", "Sustained effort 6-12 hours", "Fueling strategy execution", "Pace management over distance", "Night running if needed", "Heat/cold adaptation", "Mental endurance"], "irrelevantComponents": ["Sprint speed", "Swimming", "Cycling", "Rowing", "Short intervals", "Track speed", "Anaerobic power", "Team sports fitness"]}, "strength": {"summary": "Ultra demands leg durability for 31 miles with 8000ft gain.", "keyComponents": ["Single-leg endurance", "Downhill eccentric control", "Core running posture for hours", "Calf endurance", "Quad durability", "Hip stability", "Ankle strength"], "irrelevantComponents": ["Heavy max lifts", "Bench press", "Heavy pull-ups", "Olympic lifts", "Machine work", "Upper body max", "Grip max", "Heavy carries"]}, "climbing_technical": {"summary": "No technical climbing.", "keyComponents": ["Trail navigation", "Night running", "Aid station management"], "irrelevantComponents": ["All climbing skills"]}, "flexibility": {"summary": "Must maintain running form for hours.", "keyComponents": ["Hip flexor range", "Hamstring flexibility", "IT band maintenance", "Ankle range", "Calf flexibility", "Quad flexibility"], "irrelevantComponents": ["Full splits", "Backbends", "Shoulder range", "Wrist flexibility"]}}',
'{"cardio": [{"exerciseId": "b1000000-0000-0000-0000-000000000002", "exerciseName": "Sustained Zone 2 Run", "graduationTarget": "20 miles at zone 2 pace", "whyThisTarget": "Must sustain effort for 31 miles."}, {"exerciseId": "b1000000-0000-0000-0000-000000000003", "exerciseName": "Uphill Hike with Pack", "graduationTarget": "2000 ft gain in 60 min no pack", "whyThisTarget": "Strong uphill capacity."}], "strength": [{"exerciseId": "b2000000-0000-0000-0000-000000000002", "exerciseName": "Single-Leg Step-Down", "graduationTarget": "25 per leg", "whyThisTarget": "Leg durability for ultra distance."}], "climbing_technical": [{"exerciseId": "b3000000-0000-0000-0000-000000000002", "exerciseName": "Scramble Confidence Assessment", "graduationTarget": "1 out of 5", "whyThisTarget": "No scrambling."}], "flexibility": [{"exerciseId": "b4000000-0000-0000-0000-000000000001", "exerciseName": "Deep Squat Hold", "graduationTarget": "45 seconds", "whyThisTarget": "Maintain mobility for running form."}]}',
14, 'active');

-- 11. Colorado 14er Class 3-4
INSERT INTO validated_objectives (name, route, match_aliases, type, difficulty, description, summit_elevation_ft, total_gain_ft, distance_miles, duration_days, technical_grade, tags, target_scores, taglines, relevance_profiles, graduation_benchmarks, recommended_weeks, status) VALUES
('Colorado 14er (Class 3-4)', 'Capitol Peak / Longs Peak', '{"capitol peak", "longs peak", "14er class 3", "14er class 4", "capitol peak knife edge"}', 'scramble', 'advanced', 'Technical Colorado 14ers with exposed scrambling (Class 3-4).', 14265, 5000, 14, 1, 'Class 3-4', '["high-altitude", "exposure", "scrambling"]',
'{"cardio": 65, "strength": 50, "climbing_technical": 45, "flexibility": 35}',
'{"cardio": "Big day at altitude with scrambling", "strength": "Control on exposed rock moves", "climbing_technical": "Confident scrambling on exposure", "flexibility": "Fluid movement on ledges and ramps"}',
'{"cardio": {"summary": "Long days at altitude with significant elevation gain and scrambling.", "keyComponents": ["Zone 2 hiking endurance", "Altitude performance above 13000ft", "Sustained effort 8-12 hours", "Recovery during scrambling sections", "Uphill capacity with pack", "Cold morning starts", "Post-scramble descent endurance"], "irrelevantComponents": ["Sprint speed", "Swimming", "Cycling", "Rowing", "Short intervals", "Track speed", "Ultra distance"]}, "strength": {"summary": "Scrambling demands upper body pulling, core tension, and strong legs.", "keyComponents": ["Pull strength for scrambling", "Core stability on exposed terrain", "Single-leg power for high steps", "Grip on rock", "Push-up power for mantles", "Squat endurance", "Eccentric downhill control"], "irrelevantComponents": ["Bench press max", "Machine isolation", "Olympic lifts", "Heavy deadlift", "Cable work", "Wrist curls"]}, "climbing_technical": {"summary": "Class 3-4 scrambling with extreme exposure.", "keyComponents": ["Scrambling movement on exposed rock", "Route finding on ridges", "Balance on narrow ledges", "Confidence with extreme exposure", "Downclimbing technique", "Rock quality assessment", "Efficient movement on loose terrain"], "irrelevantComponents": ["Sport climbing above 5.6", "Crack climbing", "Aid climbing", "Ice climbing", "Multi-pitch rope management", "Anchor building", "Trad gear placement"]}, "flexibility": {"summary": "Scrambling requires hip range for high steps.", "keyComponents": ["Hip flexor range", "Hip rotation for stemming", "Ankle mobility", "Hamstring range", "Lower back flexibility", "Shoulder reach"], "irrelevantComponents": ["Full splits", "Extreme backbend", "Contortion", "Wrist flexibility", "Advanced yoga"]}}',
'{"cardio": [{"exerciseId": "b1000000-0000-0000-0000-000000000003", "exerciseName": "Uphill Hike with Pack", "graduationTarget": "1500 ft gain in 60 min with 15lb pack", "whyThisTarget": "Big approach plus scrambling day."}], "strength": [{"exerciseId": "b2000000-0000-0000-0000-000000000003", "exerciseName": "Weighted Pull-Ups", "graduationTarget": "6 bodyweight pull-ups", "whyThisTarget": "Pulling on scrambling terrain."}, {"exerciseId": "b2000000-0000-0000-0000-000000000002", "exerciseName": "Single-Leg Step-Down", "graduationTarget": "20 per leg", "whyThisTarget": "Single-leg control on exposed terrain."}], "climbing_technical": [{"exerciseId": "b3000000-0000-0000-0000-000000000002", "exerciseName": "Scramble Confidence Assessment", "graduationTarget": "4 out of 5", "whyThisTarget": "Must be confident on Class 3-4 with exposure."}], "flexibility": [{"exerciseId": "b4000000-0000-0000-0000-000000000001", "exerciseName": "Deep Squat Hold", "graduationTarget": "45 seconds", "whyThisTarget": "Hip and ankle range for scrambling."}]}',
12, 'active');

-- 12. Enchantments Traverse
INSERT INTO validated_objectives (name, route, match_aliases, type, difficulty, description, summit_elevation_ft, total_gain_ft, distance_miles, duration_days, technical_grade, tags, target_scores, taglines, relevance_profiles, graduation_benchmarks, recommended_weeks, status) VALUES
('Enchantments Traverse', 'Snow Lakes to Stuart Lake', '{"enchantments", "enchantments traverse", "enchantment lakes"}', 'hike', 'intermediate', 'Epic point-to-point traverse through the Enchantment Lakes basin. 18 miles with 4,500ft gain.', 7800, 4500, 18, 1, 'Class 1-2', '["endurance", "long-day", "alpine-lakes"]',
'{"cardio": 62, "strength": 40, "climbing_technical": 12, "flexibility": 28}',
'{"cardio": "Dawn-to-dusk mountain marathon", "strength": "Legs for endless granite slabs", "climbing_technical": "Basic scrambling and route finding", "flexibility": "Keep moving across varied terrain"}',
'{"cardio": {"summary": "18-mile traverse with 4500ft gain. Most complete it in 10-14 hours.", "keyComponents": ["Zone 2 endurance 10+ hours", "Uphill hiking stamina", "Slab hiking efficiency", "Heat management", "Fueling strategy", "Late-day endurance", "Descent durability"], "irrelevantComponents": ["Sprint speed", "Swimming", "Cycling", "Track intervals", "Short bursts", "Rowing"]}, "strength": {"summary": "Moderate leg strength for sustained hiking and boulder hopping.", "keyComponents": ["Step-up endurance", "Single-leg stability on slabs", "Core hiking posture", "Downhill knee strength", "Calf endurance", "Ankle stability on boulders"], "irrelevantComponents": ["Heavy max lifts", "Bench press", "Pull-ups", "Olympic lifts", "Machine work", "Heavy carries"]}, "climbing_technical": {"summary": "Some Class 2 scrambling over granite boulders.", "keyComponents": ["Boulder hopping", "Slab walking technique", "Basic route finding", "Trail navigation"], "irrelevantComponents": ["Rope skills", "Rock climbing", "Anchor building", "Multi-pitch", "Ice climbing", "Aid climbing", "Trad placement", "Crevasse rescue"]}, "flexibility": {"summary": "Long hiking day requires basic mobility.", "keyComponents": ["Hip flexor range", "Ankle mobility", "Hamstring flexibility", "Calf flexibility", "Knee comfort"], "irrelevantComponents": ["Full splits", "Backbend", "Shoulder range", "Wrist flexibility", "Contortion"]}}',
'{"cardio": [{"exerciseId": "b1000000-0000-0000-0000-000000000002", "exerciseName": "Sustained Zone 2 Run", "graduationTarget": "10 miles at zone 2 pace", "whyThisTarget": "Must sustain effort for 18 miles."}, {"exerciseId": "b1000000-0000-0000-0000-000000000003", "exerciseName": "Uphill Hike with Pack", "graduationTarget": "1300 ft gain in 60 min with 10lb pack", "whyThisTarget": "Sustained uphill for 4500ft."}], "strength": [{"exerciseId": "b2000000-0000-0000-0000-000000000002", "exerciseName": "Single-Leg Step-Down", "graduationTarget": "15 per leg", "whyThisTarget": "Basic leg stability."}], "climbing_technical": [{"exerciseId": "b3000000-0000-0000-0000-000000000002", "exerciseName": "Scramble Confidence Assessment", "graduationTarget": "2 out of 5", "whyThisTarget": "Minor scrambling."}], "flexibility": [{"exerciseId": "b4000000-0000-0000-0000-000000000001", "exerciseName": "Deep Squat Hold", "graduationTarget": "30 seconds", "whyThisTarget": "Basic mobility."}]}',
8, 'active');

-- 13. John Muir Trail
INSERT INTO validated_objectives (name, route, match_aliases, type, difficulty, description, summit_elevation_ft, total_gain_ft, distance_miles, duration_days, technical_grade, tags, target_scores, taglines, relevance_profiles, graduation_benchmarks, recommended_weeks, status) VALUES
('John Muir Trail', 'Happy Isles to Whitney', '{"john muir trail", "jmt", "john muir", "jmt thru-hike"}', 'backpacking', 'advanced', 'Iconic 211-mile thru-hike from Yosemite to Mt Whitney summit. 14-21 days.', 14505, 47000, 211, 18, 'Class 1', '["multi-day", "heavy-pack", "high-altitude", "endurance"]',
'{"cardio": 75, "strength": 55, "climbing_technical": 8, "flexibility": 35}',
'{"cardio": "Weeks of daily mountain miles", "strength": "Carry everything for three weeks", "climbing_technical": "Basic trail navigation only", "flexibility": "Stay injury-free for 200+ miles"}',
'{"cardio": {"summary": "JMT demands daily hiking of 12-18 miles with pack for 2-3 weeks.", "keyComponents": ["Multi-day sustained effort", "Zone 2 hiking 6-8 hours daily", "Altitude performance repeated days", "Recovery overnight", "Heavy pack endurance", "Pass climbing capacity", "Early morning fitness"], "irrelevantComponents": ["Sprint speed", "Swimming", "Cycling", "Track intervals", "Short bursts", "Rowing"]}, "strength": {"summary": "Carrying 35-45lb pack daily for weeks.", "keyComponents": ["Heavy pack squat endurance", "Step-up endurance with load", "Core stability under pack", "Downhill eccentric control", "Loaded carry capacity", "Shoulder endurance for pack", "Hip stability under load"], "irrelevantComponents": ["Bench press max", "Pull-up max", "Machine isolation", "Olympic lifts", "Bicep curls", "Cable work"]}, "climbing_technical": {"summary": "Class 1 trail.", "keyComponents": ["Trail following", "Pass navigation", "Stream crossing", "Snow field awareness"], "irrelevantComponents": ["Rock climbing", "Rope skills", "Scrambling", "Anchor building", "Ice climbing", "Multi-pitch", "Trad placement", "Crevasse rescue"]}, "flexibility": {"summary": "Weeks of daily hiking demands flexibility maintenance.", "keyComponents": ["Hip flexor maintenance", "Hamstring flexibility", "IT band care", "Ankle mobility", "Lower back health", "Calf flexibility"], "irrelevantComponents": ["Full splits", "Backbend", "Shoulder overhead", "Wrist flexibility", "Contortion"]}}',
'{"cardio": [{"exerciseId": "b1000000-0000-0000-0000-000000000001", "exerciseName": "Timed Loaded Step-Ups", "graduationTarget": "400 reps in 30 min with 30lb pack", "whyThisTarget": "Daily uphill capacity with heavy pack."}, {"exerciseId": "b1000000-0000-0000-0000-000000000002", "exerciseName": "Sustained Zone 2 Run", "graduationTarget": "12 miles at zone 2", "whyThisTarget": "Daily mileage of 12-18 miles."}], "strength": [{"exerciseId": "b2000000-0000-0000-0000-000000000001", "exerciseName": "Loaded Pack Squat", "graduationTarget": "20 reps at bodyweight", "whyThisTarget": "Heavy pack daily for weeks."}, {"exerciseId": "b2000000-0000-0000-0000-000000000004", "exerciseName": "Loaded Carry", "graduationTarget": "400m with 45lb in 10 min", "whyThisTarget": "Must carry heavy pack comfortably."}], "climbing_technical": [{"exerciseId": "b3000000-0000-0000-0000-000000000002", "exerciseName": "Scramble Confidence Assessment", "graduationTarget": "1 out of 5", "whyThisTarget": "No scrambling."}], "flexibility": [{"exerciseId": "b4000000-0000-0000-0000-000000000001", "exerciseName": "Deep Squat Hold", "graduationTarget": "45 seconds", "whyThisTarget": "Maintain mobility over weeks."}, {"exerciseId": "b4000000-0000-0000-0000-000000000002", "exerciseName": "Hip Flexor Stretch Assessment", "graduationTarget": "3 out of 5", "whyThisTarget": "Prevent hip tightness from daily heavy pack hiking."}]}',
14, 'active');

-- 14. Kilimanjaro
INSERT INTO validated_objectives (name, route, match_aliases, type, difficulty, description, summit_elevation_ft, total_gain_ft, distance_miles, duration_days, technical_grade, tags, target_scores, taglines, relevance_profiles, graduation_benchmarks, recommended_weeks, status) VALUES
('Kilimanjaro', 'Machame Route', '{"kilimanjaro", "kili", "kilimanjaro machame", "mount kilimanjaro"}', 'hike', 'intermediate', 'Highest peak in Africa via the popular Machame Route. 6-7 day trek to 19,341ft.', 19341, 13000, 37, 7, 'Class 1', '["high-altitude", "multi-day", "endurance"]',
'{"cardio": 65, "strength": 42, "climbing_technical": 10, "flexibility": 30}',
'{"cardio": "Steady daily hiking to extreme altitude", "strength": "Multi-day leg endurance", "climbing_technical": "Basic trekking skills only", "flexibility": "Move well across varied terrain"}',
'{"cardio": {"summary": "Kilimanjaro is a multi-day trek to nearly 20,000ft. Altitude is the main challenge.", "keyComponents": ["Multi-day hiking endurance", "Altitude acclimatization", "Zone 2 capacity for 6-8 hours daily", "Summit night 12-14 hour effort", "Recovery between trek days", "Cold-weather cardio", "Sustained pace at altitude"], "irrelevantComponents": ["Sprint speed", "Swimming", "Cycling power", "Track intervals", "Short bursts", "Rowing"]}, "strength": {"summary": "Moderate strength needed. Porters carry most gear.", "keyComponents": ["Step-up endurance", "Downhill knee stability", "Core hiking posture", "Single-leg balance", "Calf endurance", "Hip stability"], "irrelevantComponents": ["Heavy max lifts", "Bench press", "Pull-ups", "Olympic lifts", "Machine work", "Heavy carries", "Upper body max"]}, "climbing_technical": {"summary": "Class 1 trekking.", "keyComponents": ["Trail following", "Scree walking", "Night hiking with headlamp", "Pole walking technique"], "irrelevantComponents": ["Rock climbing", "Rope skills", "Anchor building", "Ice climbing", "Scrambling", "Multi-pitch", "Trad placement"]}, "flexibility": {"summary": "Daily hiking benefits from good basic mobility.", "keyComponents": ["Hip flexor range", "Ankle mobility", "Hamstring flexibility", "Calf flexibility", "Lower back mobility"], "irrelevantComponents": ["Full splits", "Backbend", "Shoulder range", "Wrist flexibility", "Contortion"]}}',
'{"cardio": [{"exerciseId": "b1000000-0000-0000-0000-000000000003", "exerciseName": "Uphill Hike with Pack", "graduationTarget": "1500 ft gain in 60 min with 15lb pack", "whyThisTarget": "Must sustain daily uphill effort at altitude."}, {"exerciseId": "b1000000-0000-0000-0000-000000000002", "exerciseName": "Sustained Zone 2 Run", "graduationTarget": "8 miles at zone 2", "whyThisTarget": "Aerobic base for multi-day effort."}], "strength": [{"exerciseId": "b2000000-0000-0000-0000-000000000002", "exerciseName": "Single-Leg Step-Down", "graduationTarget": "15 per leg", "whyThisTarget": "Leg stability for daily trekking."}], "climbing_technical": [{"exerciseId": "b3000000-0000-0000-0000-000000000002", "exerciseName": "Scramble Confidence Assessment", "graduationTarget": "2 out of 5", "whyThisTarget": "Minor scrambling on summit approach."}], "flexibility": [{"exerciseId": "b4000000-0000-0000-0000-000000000001", "exerciseName": "Deep Squat Hold", "graduationTarget": "30 seconds", "whyThisTarget": "Basic mobility for trekking."}]}',
10, 'active');

-- 15. Tour du Mont Blanc
INSERT INTO validated_objectives (name, route, match_aliases, type, difficulty, description, summit_elevation_ft, total_gain_ft, distance_miles, duration_days, technical_grade, tags, target_scores, taglines, relevance_profiles, graduation_benchmarks, recommended_weeks, status) VALUES
('Tour du Mont Blanc', 'Full Circuit (Counter-clockwise)', '{"tour du mont blanc", "tmb", "tmb trek", "tour mont blanc"}', 'backpacking', 'intermediate', 'Classic 105-mile circuit around the Mont Blanc massif. 10-12 days with 32,000ft total gain.', 8900, 32000, 105, 11, 'Class 1', '["multi-day", "heavy-pack", "endurance", "european-alps"]',
'{"cardio": 68, "strength": 50, "climbing_technical": 8, "flexibility": 32}',
'{"cardio": "Day after day of Alpine passes", "strength": "Sustained pack carry for two weeks", "climbing_technical": "Well-marked trail only", "flexibility": "Keep stride efficient over 100 miles"}',
'{"cardio": {"summary": "TMB demands 10-12 consecutive days of hiking 8-12 miles per day.", "keyComponents": ["Multi-day sustained effort", "Zone 2 hiking endurance daily", "Pass climbing capacity", "Recovery overnight", "Heat and weather adaptation", "Fueling strategy for days", "Sustained pace with pack"], "irrelevantComponents": ["Sprint speed", "Swimming", "Cycling", "Track intervals", "Short bursts", "Rowing"]}, "strength": {"summary": "Carrying 20-30lb pack daily for 10-12 days with major passes.", "keyComponents": ["Loaded hiking endurance", "Step-up capacity with pack", "Core under pack load", "Downhill eccentric control", "Calf endurance", "Hip stability with pack", "Shoulder endurance for pack"], "irrelevantComponents": ["Max bench press", "Heavy deadlift", "Olympic lifts", "Machine isolation", "Bicep curls", "Pull-up max"]}, "climbing_technical": {"summary": "Well-marked trail.", "keyComponents": ["Trail following", "Pass navigation", "Weather awareness", "Hut system navigation"], "irrelevantComponents": ["Rock climbing", "Rope skills", "Scrambling", "Anchor building", "Ice climbing", "Multi-pitch", "Trad placement", "Crevasse rescue"]}, "flexibility": {"summary": "10+ days of hiking demands flexibility maintenance.", "keyComponents": ["Hip flexor range", "Hamstring flexibility", "IT band care", "Ankle mobility", "Calf flexibility", "Lower back health"], "irrelevantComponents": ["Full splits", "Backbend", "Shoulder range", "Wrist flexibility", "Contortion"]}}',
'{"cardio": [{"exerciseId": "b1000000-0000-0000-0000-000000000001", "exerciseName": "Timed Loaded Step-Ups", "graduationTarget": "380 reps in 30 min with 25lb pack", "whyThisTarget": "TMB demands daily uphill capacity with pack."}, {"exerciseId": "b1000000-0000-0000-0000-000000000002", "exerciseName": "Sustained Zone 2 Run", "graduationTarget": "10 miles at zone 2", "whyThisTarget": "Base endurance for daily 8-12 mile hiking."}], "strength": [{"exerciseId": "b2000000-0000-0000-0000-000000000001", "exerciseName": "Loaded Pack Squat", "graduationTarget": "15 reps at bodyweight", "whyThisTarget": "Multi-day pack carry."}, {"exerciseId": "b2000000-0000-0000-0000-000000000004", "exerciseName": "Loaded Carry", "graduationTarget": "350m with 30lb in 10 min", "whyThisTarget": "Comfortable pack carry."}], "climbing_technical": [{"exerciseId": "b3000000-0000-0000-0000-000000000002", "exerciseName": "Scramble Confidence Assessment", "graduationTarget": "1 out of 5", "whyThisTarget": "No scrambling needed."}], "flexibility": [{"exerciseId": "b4000000-0000-0000-0000-000000000001", "exerciseName": "Deep Squat Hold", "graduationTarget": "45 seconds", "whyThisTarget": "Maintain mobility over 10+ days."}, {"exerciseId": "b4000000-0000-0000-0000-000000000002", "exerciseName": "Hip Flexor Stretch Assessment", "graduationTarget": "3 out of 5", "whyThisTarget": "Prevent hip tightness from daily pack hiking."}]}',
10, 'active');
