/**
 * Compare Grand Teton plan sessions: Sonnet vs Opus.
 *
 * Fetches the existing plan (generated by Sonnet) from Supabase,
 * regenerates each week with Opus using identical prompts,
 * and writes a markdown comparison report.
 *
 * Usage:
 *   npx tsx scripts/compare-plans.ts
 *
 * Requires .env.local with:
 *   NEXT_PUBLIC_SUPABASE_URL=...
 *   NEXT_PUBLIC_SUPABASE_ANON_KEY=...  (or SUPABASE_SERVICE_ROLE_KEY)
 *   ANTHROPIC_API_KEY=...
 */

import * as fs from "fs";
import * as path from "path";
import { createClient } from "@supabase/supabase-js";
import Anthropic from "@anthropic-ai/sdk";

// ---------- Load env from .env.local ----------
const envPath = path.join(__dirname, "..", ".env.local");
if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, "utf-8");
  for (const line of envContent.split("\n")) {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith("#")) {
      const eqIdx = trimmed.indexOf("=");
      if (eqIdx > 0) {
        const key = trimmed.slice(0, eqIdx);
        const val = trimmed.slice(eqIdx + 1);
        if (!process.env[key]) {
          process.env[key] = val;
        }
      }
    }
  }
}

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const ANTHROPIC_KEY = process.env.ANTHROPIC_API_KEY;

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error("ERROR: NEXT_PUBLIC_SUPABASE_URL and a Supabase key must be set in .env.local");
  process.exit(1);
}
if (!ANTHROPIC_KEY || ANTHROPIC_KEY === "your-anthropic-api-key") {
  console.error("ERROR: ANTHROPIC_API_KEY must be set in .env.local");
  process.exit(1);
}

// ---------- Initialize clients ----------
const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);
const anthropic = new Anthropic({ apiKey: ANTHROPIC_KEY, timeout: 180000 });

// ---------- Read PROMPT_2B_SYSTEM from prompts.ts ----------
const promptsSource = fs.readFileSync(
  path.join(__dirname, "..", "src", "lib", "prompts.ts"),
  "utf-8"
);
const prompt2bMatch = promptsSource.match(/export const PROMPT_2B_SYSTEM = `([\s\S]*?)`;/);
const PROMPT_2B_SYSTEM = prompt2bMatch?.[1] ?? "";
if (!PROMPT_2B_SYSTEM) {
  console.error("ERROR: Could not extract PROMPT_2B_SYSTEM from src/lib/prompts.ts");
  process.exit(1);
}

// ---------- Types ----------
interface DimensionScores {
  cardio: number;
  strength: number;
  climbing_technical: number;
  flexibility: number;
}

interface PlanSession {
  name: string;
  objective: string;
  estimatedMinutes: number;
  dimension: string;
  warmUp: {
    rounds: number;
    warmUpMinutes?: number;
    exercises: { name: string; reps: string }[];
  };
  training: {
    exerciseNumber: number;
    description: string;
    details: string;
    durationMinutes?: number;
    intensityNote: string | null;
  }[];
  cooldown: string | null;
  cooldownMinutes?: number;
}

interface WeeklyTarget {
  id: string;
  plan_id: string;
  week_number: number;
  week_start: string;
  week_type: string;
  total_hours: number | null;
  expected_scores: DimensionScores;
  sessions: PlanSession[];
}

const DIMENSIONS = ["cardio", "strength", "climbing_technical", "flexibility"] as const;
const MAX_CONCURRENT = 3;

// ---------- Claude API helper ----------
async function callClaudeOpus(systemPrompt: string, userMessage: string): Promise<string> {
  const response = await anthropic.messages.create({
    model: "claude-opus-4-20250514",
    max_tokens: 8192,
    system: [{ type: "text" as const, text: systemPrompt, cache_control: { type: "ephemeral" as const } }],
    messages: [{ role: "user" as const, content: userMessage }],
  });

  const textBlock = response.content.find((b) => b.type === "text");
  if (!textBlock || textBlock.type !== "text") {
    throw new Error("No text response from Claude");
  }
  return textBlock.text;
}

function parseClaudeJSON<T>(text: string): T {
  const jsonMatch = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  const jsonStr = jsonMatch ? jsonMatch[1].trim() : text.trim();
  return JSON.parse(jsonStr) as T;
}

// ---------- Progress fractions (ported from scoring.ts) ----------
function dimensionProgressFractions(
  currentScores: DimensionScores,
  targetScores: DimensionScores,
  weekNumber: number,
  totalWeeks: number
): Record<string, { fraction: number; maintenance: boolean }> {
  const result: Record<string, { fraction: number; maintenance: boolean }> = {};

  for (const dim of DIMENSIONS) {
    const current = currentScores[dim];
    const target = targetScores[dim];

    if (target > 0 && current >= 1.25 * target) {
      result[dim] = { fraction: 60, maintenance: true };
      continue;
    }

    let floor: number;
    if (target <= 0) {
      floor = 0.5;
    } else if (current >= target) {
      floor = 0.8;
    } else {
      floor = Math.max(0.5, current / target);
    }

    const progress = floor + (1 - floor) * (weekNumber / totalWeeks);
    result[dim] = {
      fraction: Math.round(Math.min(progress, 1.0) * 100),
      maintenance: false,
    };
  }

  return result;
}

// ---------- Build user message (identical to generate-all-sessions) ----------
function buildUserMessage(
  profile: { training_days_per_week?: number; equipment_access?: string[]; location?: string } | null,
  objective: Record<string, unknown>,
  weekTarget: Record<string, unknown>,
  totalWeeks: number,
  programmingHints: Record<string, unknown> | null,
  climbingRole: string | null,
  daysPerWeek: number
): string {
  const weekNumber = weekTarget.week_number as number;

  const programmingHintsBlock = programmingHints
    ? `\nATHLETE PROFILE (from assessment):\n${JSON.stringify(programmingHints, null, 2)}\nClimbing role: ${climbingRole || "not specified"}\n\nUse the programming hints to adapt session content to this specific athlete:\n- Start exercises at the recommended intensity level\n- Allocate time across dimensions as recommended\n- Apply specific adaptations noted above\n- If a dimension is flagged as "maintain", prescribe maintenance-level volume\n`
    : "";

  return `Athlete profile: Available ${daysPerWeek} days/week. Generate EXACTLY ${daysPerWeek} sessions total — no more, no fewer. Equipment: ${(profile?.equipment_access || []).join(", ") || "basic gym equipment"}. Location: ${profile?.location || "not specified"}. Injuries: none.
${programmingHintsBlock}
Objective: ${objective.name}. Type: ${objective.type}. Target date: ${objective.target_date}. Distance: ${objective.distance_miles || "N/A"} miles. Elevation gain: ${objective.elevation_gain_ft || "N/A"} ft. Technical grade: ${objective.technical_grade || "N/A"}.

Current scores: Cardio ${objective.current_cardio_score}, Strength ${objective.current_strength_score}, Climbing/Technical ${objective.current_climbing_score}, Flexibility ${objective.current_flexibility_score}.
Target scores: Cardio ${objective.target_cardio_score}, Strength ${objective.target_strength_score}, Climbing/Technical ${objective.target_climbing_score}, Flexibility ${objective.target_flexibility_score}.

THIS IS WEEK ${weekNumber} of ${totalWeeks} total weeks.
Week type: ${weekTarget.week_type}.
Week start date: ${weekTarget.week_start}.
Target hours: ${weekTarget.total_hours}.
Expected scores this week: ${JSON.stringify(weekTarget.expected_scores)}.

Graduation benchmarks: ${JSON.stringify(objective.graduation_benchmarks)}

Relevance profiles: ${JSON.stringify(objective.relevance_profiles)}

${buildProgressFractionBlock(objective, weekNumber, totalWeeks)}`;
}

function buildProgressFractionBlock(
  objective: Record<string, unknown>,
  weekNumber: number,
  totalWeeks: number
): string {
  const currentScores: DimensionScores = {
    cardio: (objective.current_cardio_score as number) || 0,
    strength: (objective.current_strength_score as number) || 0,
    climbing_technical: (objective.current_climbing_score as number) || 0,
    flexibility: (objective.current_flexibility_score as number) || 0,
  };
  const targetScores: DimensionScores = {
    cardio: (objective.target_cardio_score as number) || 0,
    strength: (objective.target_strength_score as number) || 0,
    climbing_technical: (objective.target_climbing_score as number) || 0,
    flexibility: (objective.target_flexibility_score as number) || 0,
  };
  const fractions = dimensionProgressFractions(currentScores, targetScores, weekNumber, totalWeeks);

  const dimLabels: Record<string, string> = {
    cardio: "Cardio",
    strength: "Strength",
    climbing_technical: "Climbing/Technical",
    flexibility: "Flexibility",
  };

  const lines: string[] = [];
  const maintenanceDims: string[] = [];

  for (const [dim, label] of Object.entries(dimLabels)) {
    const prog = fractions[dim];
    const current = currentScores[dim as keyof DimensionScores];
    const target = targetScores[dim as keyof DimensionScores];

    if (prog.maintenance) {
      const performanceRatio = target > 0 ? Math.round((current / target) * 100) : 100;
      lines.push(`- ${label}: MAINTENANCE MODE (1 session/week, 60% volume) — current ${current} vs target ${target}. Athlete performs at ~${performanceRatio}% of graduation benchmarks. Prescribe the single session at this higher level, not at graduation target level.`);
      maintenanceDims.push(label);
    } else if (current >= target) {
      lines.push(`- ${label}: ${prog.fraction}% (already meets target — maintenance with slight progression)`);
    } else {
      lines.push(`- ${label}: ${prog.fraction}%`);
    }
  }

  let result = `Per-dimension progress fractions for Week ${weekNumber} (percentage of graduation targets this week's sessions should reach):
${lines.join("\n")}

IMPORTANT: These percentages reflect the athlete's CURRENT fitness level. Do NOT prescribe beginner-level training for dimensions where the athlete is already strong. Match session intensity to the progress fraction shown.`;

  if (maintenanceDims.length > 0) {
    result += `\n\nMAINTENANCE REALLOCATION: ${maintenanceDims.join(", ")} ${maintenanceDims.length === 1 ? "is" : "are"} in maintenance mode. Reallocate freed training time to dimensions furthest below their target scores, prioritizing the dimension with the highest target score.`;
  }

  return result;
}

// ---------- Session duration calculation (ported from scoring.ts) ----------
function calculateSessionMinutes(session: PlanSession): number {
  const warmUp = session.warmUp?.warmUpMinutes ?? 10;
  const training = session.training?.reduce(
    (sum, ex) => sum + (ex.durationMinutes ?? 0),
    0
  ) ?? 0;
  const cooldown = session.cooldownMinutes ?? 5;
  const total = warmUp + training + cooldown;
  if (training === 0) return session.estimatedMinutes || 45;
  return Math.round(total);
}

function calculateAllSessionMinutes(sessions: PlanSession[]): void {
  for (const session of sessions) {
    session.estimatedMinutes = calculateSessionMinutes(session);
  }
}

// ---------- Markdown report generation ----------
function formatSession(session: PlanSession, index: number): string {
  const lines: string[] = [];
  lines.push(`**Session ${index + 1}: ${session.name}** (${session.dimension}, ~${session.estimatedMinutes} min)`);
  lines.push(`> _${session.objective}_`);
  lines.push("");

  if (session.warmUp?.exercises?.length > 0) {
    lines.push(`Warm-up (~${session.warmUp.warmUpMinutes ?? "?"}min):`);
    for (const ex of session.warmUp.exercises) {
      lines.push(`- ${ex.name}: ${ex.reps}`);
    }
    lines.push("");
  }

  for (const ex of session.training) {
    const dur = ex.durationMinutes ? ` (~${ex.durationMinutes}min)` : "";
    const intensity = ex.intensityNote ? ` _[${ex.intensityNote}]_` : "";
    lines.push(`${ex.exerciseNumber}. **${ex.description}**${dur}${intensity}`);
    lines.push(`   ${ex.details}`);
  }

  if (session.cooldown) {
    lines.push("");
    lines.push(`Cooldown (~${session.cooldownMinutes ?? "?"}min): ${session.cooldown}`);
  }

  return lines.join("\n");
}

function formatWeekComparison(
  weekNumber: number,
  weekStart: string,
  weekType: string,
  expectedScores: DimensionScores,
  targetHours: number | null,
  sonnetSessions: PlanSession[],
  opusSessions: PlanSession[]
): string {
  const lines: string[] = [];
  lines.push(`## Week ${weekNumber} (${weekStart}, ${weekType})`);
  lines.push("");
  lines.push(`Expected scores: Cardio ${expectedScores.cardio} | Strength ${expectedScores.strength} | Climbing ${expectedScores.climbing_technical} | Flexibility ${expectedScores.flexibility}`);
  lines.push(`Target hours: ${targetHours ?? "?"}`);
  lines.push("");

  const sonnetTotal = sonnetSessions.reduce((s, sess) => s + (sess.estimatedMinutes || 0), 0);
  const opusTotal = opusSessions.reduce((s, sess) => s + (sess.estimatedMinutes || 0), 0);
  const diff = opusTotal - sonnetTotal;
  const diffStr = diff > 0 ? `+${diff}` : `${diff}`;
  lines.push(`| Metric | Sonnet | Opus | Delta |`);
  lines.push(`|--------|--------|------|-------|`);
  lines.push(`| Total minutes | ${sonnetTotal} | ${opusTotal} | ${diffStr} |`);
  lines.push(`| Session count | ${sonnetSessions.length} | ${opusSessions.length} | ${opusSessions.length - sonnetSessions.length === 0 ? "—" : opusSessions.length - sonnetSessions.length} |`);

  for (const dim of DIMENSIONS) {
    const sSessions = sonnetSessions.filter(s => s.dimension === dim);
    const oSessions = opusSessions.filter(s => s.dimension === dim);
    const sMin = sSessions.reduce((sum, s) => sum + (s.estimatedMinutes || 0), 0);
    const oMin = oSessions.reduce((sum, s) => sum + (s.estimatedMinutes || 0), 0);
    const label = dim === "climbing_technical" ? "Climbing" : dim.charAt(0).toUpperCase() + dim.slice(1);
    lines.push(`| ${label} sessions | ${sSessions.length} (${sMin}min) | ${oSessions.length} (${oMin}min) | ${oMin - sMin === 0 ? "—" : `${oMin - sMin > 0 ? "+" : ""}${oMin - sMin}min`} |`);
  }
  lines.push("");

  const allDims = new Set([
    ...sonnetSessions.map(s => s.dimension),
    ...opusSessions.map(s => s.dimension),
  ]);

  for (const dim of allDims) {
    const sSessions = sonnetSessions.filter(s => s.dimension === dim);
    const oSessions = opusSessions.filter(s => s.dimension === dim);
    const maxLen = Math.max(sSessions.length, oSessions.length);

    for (let i = 0; i < maxLen; i++) {
      const label = dim === "climbing_technical" ? "Climbing/Technical" : dim.charAt(0).toUpperCase() + dim.slice(1);
      lines.push(`### ${label} — Session ${i + 1}`);
      lines.push("");

      if (sSessions[i] && oSessions[i]) {
        lines.push("<details><summary>Sonnet</summary>");
        lines.push("");
        lines.push(formatSession(sSessions[i], i));
        lines.push("</details>");
        lines.push("");
        lines.push("<details><summary>Opus</summary>");
        lines.push("");
        lines.push(formatSession(oSessions[i], i));
        lines.push("</details>");
        lines.push("");

        const sExercises = sSessions[i].training.map(t => t.description.toLowerCase());
        const oExercises = oSessions[i].training.map(t => t.description.toLowerCase());
        const onlySonnet = sExercises.filter(e => !oExercises.includes(e));
        const onlyOpus = oExercises.filter(e => !sExercises.includes(e));

        if (onlySonnet.length > 0 || onlyOpus.length > 0) {
          lines.push("**Exercise differences:**");
          if (onlySonnet.length > 0) lines.push(`- Sonnet only: ${onlySonnet.join(", ")}`);
          if (onlyOpus.length > 0) lines.push(`- Opus only: ${onlyOpus.join(", ")}`);
          lines.push("");
        }
      } else if (sSessions[i]) {
        lines.push("**Sonnet only** (no Opus equivalent):");
        lines.push(formatSession(sSessions[i], i));
        lines.push("");
      } else if (oSessions[i]) {
        lines.push("**Opus only** (no Sonnet equivalent):");
        lines.push(formatSession(oSessions[i], i));
        lines.push("");
      }
    }
  }

  lines.push("---");
  return lines.join("\n");
}

function generateAggregateSummary(
  weekComparisons: { weekNumber: number; sonnet: PlanSession[]; opus: PlanSession[] }[]
): string {
  const lines: string[] = [];
  lines.push("## Aggregate Analysis");
  lines.push("");

  let totalSonnetMin = 0;
  let totalOpusMin = 0;
  for (const wc of weekComparisons) {
    totalSonnetMin += wc.sonnet.reduce((s, sess) => s + (sess.estimatedMinutes || 0), 0);
    totalOpusMin += wc.opus.reduce((s, sess) => s + (sess.estimatedMinutes || 0), 0);
  }
  lines.push(`### Total Volume`);
  lines.push(`- Sonnet: ${totalSonnetMin} min (${(totalSonnetMin / 60).toFixed(1)} hrs)`);
  lines.push(`- Opus: ${totalOpusMin} min (${(totalOpusMin / 60).toFixed(1)} hrs)`);
  lines.push(`- Difference: ${totalOpusMin - totalSonnetMin > 0 ? "+" : ""}${totalOpusMin - totalSonnetMin} min (${((totalOpusMin - totalSonnetMin) / 60).toFixed(1)} hrs)`);
  lines.push("");

  lines.push(`### Dimension Time Allocation`);
  lines.push("");
  lines.push("| Dimension | Sonnet (min) | Sonnet % | Opus (min) | Opus % | Delta |");
  lines.push("|-----------|-------------|----------|-----------|--------|-------|");

  for (const dim of DIMENSIONS) {
    const sMin = weekComparisons.flatMap(wc => wc.sonnet).filter(s => s.dimension === dim).reduce((sum, s) => sum + (s.estimatedMinutes || 0), 0);
    const oMin = weekComparisons.flatMap(wc => wc.opus).filter(s => s.dimension === dim).reduce((sum, s) => sum + (s.estimatedMinutes || 0), 0);
    const sPct = totalSonnetMin > 0 ? ((sMin / totalSonnetMin) * 100).toFixed(1) : "0";
    const oPct = totalOpusMin > 0 ? ((oMin / totalOpusMin) * 100).toFixed(1) : "0";
    const label = dim === "climbing_technical" ? "Climbing/Technical" : dim.charAt(0).toUpperCase() + dim.slice(1);
    const delta = oMin - sMin;
    lines.push(`| ${label} | ${sMin} | ${sPct}% | ${oMin} | ${oPct}% | ${delta > 0 ? "+" : ""}${delta} |`);
  }
  lines.push("");

  const sonnetExercises = new Set<string>();
  const opusExercises = new Set<string>();
  for (const wc of weekComparisons) {
    for (const s of wc.sonnet) for (const t of s.training) sonnetExercises.add(t.description.toLowerCase());
    for (const s of wc.opus) for (const t of s.training) opusExercises.add(t.description.toLowerCase());
  }
  const common = [...sonnetExercises].filter(e => opusExercises.has(e));
  const sonnetOnly = [...sonnetExercises].filter(e => !opusExercises.has(e));
  const opusOnly = [...opusExercises].filter(e => !sonnetExercises.has(e));

  lines.push(`### Exercise Vocabulary`);
  lines.push(`- Sonnet unique exercises: ${sonnetExercises.size}`);
  lines.push(`- Opus unique exercises: ${opusExercises.size}`);
  lines.push(`- In common: ${common.length}`);
  lines.push(`- Sonnet-only: ${sonnetOnly.length}`);
  lines.push(`- Opus-only: ${opusOnly.length}`);
  lines.push("");

  if (sonnetOnly.length > 0) {
    lines.push("**Sonnet-only exercises:**");
    for (const e of sonnetOnly.sort()) lines.push(`- ${e}`);
    lines.push("");
  }
  if (opusOnly.length > 0) {
    lines.push("**Opus-only exercises:**");
    for (const e of opusOnly.sort()) lines.push(`- ${e}`);
    lines.push("");
  }

  lines.push(`### Coaching Voice Samples (Session Objectives)`);
  lines.push("");
  const sonnetObjectives = weekComparisons.flatMap(wc => wc.sonnet.map(s => ({ week: wc.weekNumber, name: s.name, obj: s.objective })));
  const opusObjectives = weekComparisons.flatMap(wc => wc.opus.map(s => ({ week: wc.weekNumber, name: s.name, obj: s.objective })));

  const sampleWeeks = [
    weekComparisons[0]?.weekNumber,
    weekComparisons[Math.floor(weekComparisons.length / 2)]?.weekNumber,
    weekComparisons[weekComparisons.length - 1]?.weekNumber,
  ].filter(Boolean);
  for (const wn of sampleWeeks) {
    const sObjs = sonnetObjectives.filter(o => o.week === wn).slice(0, 2);
    const oObjs = opusObjectives.filter(o => o.week === wn).slice(0, 2);
    if (sObjs.length > 0 || oObjs.length > 0) {
      lines.push(`**Week ${wn}:**`);
      for (const s of sObjs) lines.push(`- Sonnet "${s.name}": _${s.obj}_`);
      for (const o of oObjs) lines.push(`- Opus "${o.name}": _${o.obj}_`);
      lines.push("");
    }
  }

  return lines.join("\n");
}

// ---------- Main ----------
async function main() {
  console.log("🏔️  Comparing Grand Teton plans: Sonnet vs Opus\n");

  // 1. Find a Grand Teton plan
  console.log("Fetching plans from Supabase...");
  const { data: plans, error: plansErr } = await supabase
    .from("training_plans")
    .select("*")
    .eq("status", "active");

  if (plansErr || !plans || plans.length === 0) {
    console.error("No active plans found.", plansErr?.message);
    process.exit(1);
  }

  // Get all objectives to find Grand Teton
  let grandTetonPlan: Record<string, unknown> | null = null;
  let objective: Record<string, unknown> | null = null;

  for (const plan of plans) {
    const { data: obj } = await supabase
      .from("objectives")
      .select("*")
      .eq("id", plan.objective_id)
      .single();

    if (obj && (obj.name as string || "").toLowerCase().includes("teton")) {
      objective = obj;
      grandTetonPlan = plan;
      break;
    }
  }

  if (!grandTetonPlan || !objective) {
    console.error("No Grand Teton plan found. Available plans:");
    for (const p of plans) {
      const { data: obj } = await supabase.from("objectives").select("name").eq("id", p.objective_id).single();
      console.log(`  - ${obj?.name || "unknown"} (plan ${p.id})`);
    }
    process.exit(1);
  }

  console.log(`Found: "${objective.name}" (plan: ${grandTetonPlan.id})`);
  console.log(`  Target scores: C${objective.target_cardio_score} S${objective.target_strength_score} CT${objective.target_climbing_score} F${objective.target_flexibility_score}`);
  console.log(`  Current scores: C${objective.current_cardio_score} S${objective.current_strength_score} CT${objective.current_climbing_score} F${objective.current_flexibility_score}`);

  // 2. Fetch weekly targets
  const { data: weeks, error: weeksErr } = await supabase
    .from("weekly_targets")
    .select("*")
    .eq("plan_id", grandTetonPlan.id)
    .order("week_number");

  if (weeksErr || !weeks || weeks.length === 0) {
    console.error("No weekly targets found.", weeksErr?.message);
    process.exit(1);
  }

  const weeksWithSessions = weeks.filter(
    (w: WeeklyTarget) => w.sessions && (w.sessions as PlanSession[]).length > 0
  ) as WeeklyTarget[];
  console.log(`  Total weeks: ${weeks.length}, with sessions: ${weeksWithSessions.length}`);

  if (weeksWithSessions.length === 0) {
    console.error("No weeks have sessions generated yet.");
    process.exit(1);
  }

  // 3. Fetch profile
  const { data: profile } = await supabase
    .from("profiles")
    .select("*")
    .eq("id", objective.user_id)
    .single();

  // 4. Extract plan data
  const planData = grandTetonPlan.plan_data as Record<string, unknown> | null;
  const programmingHints = (planData?.programmingHints as Record<string, unknown>) || null;
  const climbingRole = (objective.climbing_role as string) || null;
  const daysPerWeek = (profile?.training_days_per_week as number) || 5;
  const totalWeeks = weeks.length;

  // 5. Generate Opus sessions for each week
  console.log(`\nGenerating Opus sessions for ${weeksWithSessions.length} weeks (concurrency: ${MAX_CONCURRENT})...\n`);

  const weekComparisons: { weekNumber: number; sonnet: PlanSession[]; opus: PlanSession[] }[] = [];
  const errors: { weekNumber: number; error: string }[] = [];

  // Process in batches of MAX_CONCURRENT
  for (let i = 0; i < weeksWithSessions.length; i += MAX_CONCURRENT) {
    const batch = weeksWithSessions.slice(i, i + MAX_CONCURRENT);

    const results = await Promise.allSettled(
      batch.map(async (weekTarget) => {
        const wn = weekTarget.week_number;
        console.log(`  Week ${wn}/${totalWeeks} — generating...`);

        const userMessage = buildUserMessage(
          profile as { training_days_per_week?: number; equipment_access?: string[]; location?: string } | null,
          objective!,
          weekTarget as unknown as Record<string, unknown>,
          totalWeeks,
          programmingHints,
          climbingRole,
          daysPerWeek
        );

        const responseText = await callClaudeOpus(PROMPT_2B_SYSTEM, userMessage);
        const result = parseClaudeJSON<{ sessions: PlanSession[] }>(responseText);
        calculateAllSessionMinutes(result.sessions);

        return { weekNumber: wn, sonnet: weekTarget.sessions, opus: result.sessions };
      })
    );

    for (const result of results) {
      if (result.status === "fulfilled") {
        const { weekNumber, sonnet, opus } = result.value;
        weekComparisons.push({ weekNumber, sonnet, opus });
        const sMin = sonnet.reduce((s: number, sess: PlanSession) => s + (sess.estimatedMinutes || 0), 0);
        const oMin = opus.reduce((s: number, sess: PlanSession) => s + (sess.estimatedMinutes || 0), 0);
        console.log(`  Week ${weekNumber} ✓ (Sonnet: ${sMin}min/${sonnet.length}s, Opus: ${oMin}min/${opus.length}s)`);
      } else {
        const msg = result.reason instanceof Error ? result.reason.message : String(result.reason);
        console.log(`  Week ✗ Error: ${msg.slice(0, 120)}`);
        errors.push({ weekNumber: -1, error: msg });
      }
    }
  }

  if (weekComparisons.length === 0) {
    console.error("\nNo weeks were successfully generated. Cannot create report.");
    process.exit(1);
  }

  // 6. Generate markdown report
  console.log(`\nGenerating comparison report...`);

  const reportLines: string[] = [];
  reportLines.push("# Sonnet vs Opus: Grand Teton Training Plan Comparison");
  reportLines.push("");
  reportLines.push(`_Generated: ${new Date().toISOString()}_`);
  reportLines.push("");
  reportLines.push(`**Objective:** ${objective.name}`);
  reportLines.push(`**Target date:** ${objective.target_date}`);
  reportLines.push(`**Total weeks:** ${totalWeeks}`);
  reportLines.push(`**Weeks compared:** ${weekComparisons.length}${errors.length > 0 ? ` (${errors.length} failed)` : ""}`);
  reportLines.push(`**Target scores:** Cardio ${objective.target_cardio_score} | Strength ${objective.target_strength_score} | Climbing ${objective.target_climbing_score} | Flexibility ${objective.target_flexibility_score}`);
  reportLines.push(`**Current scores:** Cardio ${objective.current_cardio_score} | Strength ${objective.current_strength_score} | Climbing ${objective.current_climbing_score} | Flexibility ${objective.current_flexibility_score}`);
  if (climbingRole) reportLines.push(`**Climbing role:** ${climbingRole}`);
  reportLines.push("");

  reportLines.push(generateAggregateSummary(weekComparisons));
  reportLines.push("");
  reportLines.push("---");
  reportLines.push("");
  reportLines.push("# Per-Week Comparison");
  reportLines.push("");

  for (const wc of weekComparisons.sort((a, b) => a.weekNumber - b.weekNumber)) {
    const weekTarget = weeksWithSessions.find(w => w.week_number === wc.weekNumber)!;
    reportLines.push(formatWeekComparison(
      wc.weekNumber,
      weekTarget.week_start,
      weekTarget.week_type,
      weekTarget.expected_scores,
      weekTarget.total_hours,
      wc.sonnet,
      wc.opus
    ));
    reportLines.push("");
  }

  if (errors.length > 0) {
    reportLines.push("## Errors");
    for (const e of errors) {
      reportLines.push(`- Week ${e.weekNumber}: ${e.error.slice(0, 200)}`);
    }
  }

  // 7. Write report
  const reportsDir = path.join(__dirname, "..", "reports");
  if (!fs.existsSync(reportsDir)) fs.mkdirSync(reportsDir, { recursive: true });
  const reportPath = path.join(reportsDir, "sonnet-vs-opus-grand-teton.md");
  fs.writeFileSync(reportPath, reportLines.join("\n"), "utf-8");
  console.log(`\n✅ Report written to: ${reportPath}`);
  console.log(`   ${weekComparisons.length} weeks compared, ${errors.length} errors.`);
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
